### ISSUE TITLE
nodejs vs node

### ISSUE THREAD

**Issue by gpotter2** [ashiina/lambda-local#40]
For now the program has been using this to start lambda-local:

`#!/usr/bin/env node`

But the new nodejs versions are now published with the "nodejs" command instead of only "node".
So for now you had to link node to nodejs...

I guess we should replace node by nodejs in there...

**Comment by ashiina** [comment]
As far as I know the `nodejs` command is not a version difference, but a Linux distro differnece. It seems that Debian installs node.js as a `nodejs` command, due to package name conflicts.
https://nodejs.org/en/download/package-manager/
It says here: 

> The nodejs-legacy package installs a node symlink that is needed by many modules to build and run correctly. The Node.js modules available in the distribution official repositories do not need it.

So I think this is the position of the official node.js, and individual modules such as `lambda-local` do not have to support the `nodejs` command.

**Comment by ashiina** [comment]
Let me know if I am mistaken. Otherwise I would close this issue. Thanks!

**Comment by ashiina** [comment]
By changing `#!/usr/bin/env node` to `#!/usr/bin/env nodejs` , the majority of users who have the `node` command will not be able to use it anymore. And unlike Debian users, we(majority users using `node`) don't have a legacy package to install a `nodejs` command.
So it doesn't make sense to replace this.

Also, I took a look at other popular node.js projects, and they seem fine using `node`. 
https://github.com/mochajs/mocha/blob/master/bin/mocha
https://github.com/shelljs/shelljs/blob/master/bin/shjs

Given the above I still do not see any reason to replace it...

**Comment by gpotter2** [comment]
Fine then :)
