### ISSUE TITLE
Failing when trying to access metadataservice

### ISSUE THREAD

**Issue by spruce** [ashiina/lambda-local#45]
Hey,
first of all thanks for such a nice tool.

When trying to access some metadata on a host which is not amazon. it fails to access the host because it is not reachable (this ip is hardcoded in aws-sdk/lib/metadata_service.js)

Error: connect EHOSTUNREACH 169.254.169.254:80 - Local (192.168.178.134:51835)
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at connect (net.js:844:14)
    at net.js:940:9
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickDomainCallback (node.js:403:13)

**Comment by ashiina** [comment]
@spruce 
Thanks!
The AWS metadata is only accessible from an Amazon EC2 instance. The IP `169.254.169.254` is a private IP within your AWS network, so it cannot be accessed from anywhere else. 
It is hardcoded in the `aws-sdk` because that IP address is the rule. 
The document is here: 
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

**Comment by ashiina** [comment]
I will be closing the issue since the official documentation explains it and is unrelated to `lambda-local`.
