### ISSUE TITLE
Format for env variable array?

### ISSUE THREAD

**Issue by raphaellondner-mongodb** [ashiina/lambda-local#73]
This is probably very obvious, but I can't get that to work. I've tried the following:

`lambda-local -l sms.js -e event.json -E  {\"TWILIO_ACCOUNT_SID\":\"test\",\"TWILIO_AUTH_TOKEN\":\"test\"}`

as well as variations of JSON array, to no avail. 

Can you update the Readme file and clarify how to handle multiple environment variables/JSON keys?

**Comment by iamkirkbater** [comment]
Not the maintainer, but the way we have our lambda set up is to have the main handler in a `main/handler.js` file.  For testing, we have an `index.js` file that loads the `dotenv` library, and then just exports the handler.

So our file structure:

```
./
  - index.js
  - main/
    | - handler.js
```

main/handler.js:
```
const handler = (event, context) => {
  // all of the code
}
module.exports = {
  handler,
};
```

index.js:
```
require('dotenv').config();

const handler = require('./main/handler.js');

module.exports = handler;
```


So when we run the file on Lambda, we run it directly from `main/handler.js`, where when we run it from lambda-local we run it from `index.js` so that it loads all of our test environment variables from the `.env` file.

I know it doesn't fix the problem, but hopefully it can help.

**Comment by ashiina** [comment]
@raphaellondner-mongodb Escaping the comma seems to be the answer, as such:

```
lambda-local -l sms.js -e event.json -E {\"TWILIO_ACCOUNT_SID\":\"test\"\,\"TWILIO_AUTH_TOKEN\":\"test\"}
```

I'll update the README to clarify that. Also, in my coming release (coming out today) I fixed it to catch the JSON exception, so that you have a better idea of what is wrong.

**Comment by raphaellondner-mongodb** [comment]
Of course, I should have thought about that... That works, thank you @ashiina! 

BTW, do you know when the next release will be available on npmjs.com?
